#!/usr/bin/env python3
# [Arcade] Embed the CRT shaders in svn1749/src/sdl/crt/ as C strings, so the
# program carries them and nothing extra has to be installed beside it.
# Writes svn1749/src/sdl/ogl_crt_glsl.h.  The order here is the order of the
# gr_shader values after Off, and must match grshader_cons_t (hw_main.c).
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "svn1749", "src", "sdl")
SHADERS = [
    # file,            C name,      linear sampling (RetroArch preset's filter_linear)
    ("zfast_crt.glsl",  "zfast",     True),
    ("crt-pi.glsl",     "crtpi",     True),
    ("crt-lottes.glsl", "lottes",    False),
    ("crt-geom.glsl",   "geom",      False),
]

def c_string(text):
    out = []
    for line in text.split("\n"):
        line = line.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "    ")
        out.append('    "%s\\n"' % line)
    return "\n".join(out)

parts = ["// Generated by tools/glsl2c.py from sdl/crt/*.glsl -- do not edit.\n"
         "// Licences are in each shader's own header and in sdl/crt/README.\n"]
for fname, name, _ in SHADERS:
    with open(os.path.join(ROOT, "crt", fname), encoding="ascii") as f:
        text = f.read().replace("\r\n", "\n")
    parts.append("static const char crt_src_%s[] =\n%s;\n" % (name, c_string(text)))

parts.append("static const crt_shader_def_t crt_shader_defs[] = {")
for fname, name, linear in SHADERS:
    parts.append('    { "%s", crt_src_%s, %d },' % (fname, name, 1 if linear else 0))
parts.append("};\n")

with open(os.path.join(ROOT, "ogl_crt_glsl.h"), "w", encoding="ascii") as f:
    f.write("\n".join(parts))
print("wrote", os.path.join(ROOT, "ogl_crt_glsl.h"))
