#!/usr/bin/env python3
# [Arcade] Embed the post-process shaders in svn1749/src/sdl/shaders/ as C
# strings, so the program carries them and nothing extra has to be installed
# beside it.  Writes svn1749/src/sdl/ogl_shader_glsl.h.
#
# The order of SHADERS is the order of the gr_shader values after Off.  The
# labels must match grshader_cons_t in hardware/hw_main.c; ogl_shader.c
# checks that at startup and says so in the log if they drift.
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "svn1749", "src", "sdl")

# label, file, extra defines, linear sampling, downsample to ~200 lines, needs the palette lookup
SHADERS = [
    ("zfast CRT",     "zfast_crt.glsl",     "",               True,  True,  False),
    ("CRT-Pi",        "crt-pi.glsl",        "",               True,  True,  False),
    ("CRT-Lottes",    "crt-lottes.glsl",    "",               False, True,  False),
    ("CRT-Geom",      "crt-geom.glsl",      "",               False, True,  False),
    ("FXAA",          "fxaa.glsl",          "",               True,  False, False),
    ("Software Look", "software-look.glsl", "",               False, False, True),
    ("VHS",           "vhs.glsl",           "",               True,  False, False),
    ("Greyscale",     "colour.glsl",        "#define LOOK 1\\n", False, False, False),
    ("Sepia",         "colour.glsl",        "#define LOOK 2\\n", False, False, False),
    ("Night Vision",  "colour.glsl",        "#define LOOK 3\\n", False, False, False),
    ("Game Boy",      "game-boy.glsl",      "",               False, True,  False),
]

def c_string(text):
    out = []
    for line in text.split("\n"):
        line = line.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "    ")
        out.append('    "%s\\n"' % line)
    return "\n".join(out)

def c_name(fname):
    return "src_" + fname.replace(".glsl", "").replace("-", "_")

parts = ["// Generated by tools/glsl2c.py from sdl/shaders/*.glsl -- do not edit.\n"
         "// Licences are in each shader's own header and in sdl/shaders/README.\n"]
done = set()
for _, fname, _, _, _, _ in SHADERS:
    if fname in done:
        continue
    done.add(fname)
    with open(os.path.join(ROOT, "shaders", fname), encoding="ascii") as f:
        text = f.read().replace("\r\n", "\n")
    parts.append("static const char %s[] =\n%s;\n" % (c_name(fname), c_string(text)))

parts.append("static const shader_def_t shader_defs[] = {")
parts.append("    // label, file, source, defines, linear, downsample, palette")
for label, fname, defines, linear, down, pal in SHADERS:
    parts.append('    { "%s", "%s", %s, "%s", %d, %d, %d },'
                 % (label, fname, c_name(fname), defines, linear, down, pal))
parts.append("};\n")

out = os.path.join(ROOT, "ogl_shader_glsl.h")
with open(out, "w", encoding="ascii") as f:
    f.write("\n".join(parts))
print("wrote", out)
